# Generated by Django 2.0.4 on 2018-05-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conteudo',
            new_name='text',
        ),
    ]
