# Generated by Django 2.0.4 on 2018-05-10 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20180510_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linguagem',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
