# Generated by Django 2.0.4 on 2018-05-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_post_linguagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paste_title', models.CharField(max_length=50)),
                ('paste_language', models.CharField(max_length=50)),
                ('paste_data', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
